### ISSUE TITLE
ci: Dependabot not working

### ISSUE THREAD

**Issue by samuelburnham** [lurk-lab/arecibo#208]
A `dependabot.yml` was added four months ago in #4, but doesn't seem to have created any pull requests for Cargo or GitHub Actions. It should be scanning weekly for GitHub Actions, but we still have an outdated `actions/checkout` action in https://github.com/lurk-lab/arecibo/blob/dev/.github/workflows/rust.yml#L29

An identical configuration appears to working at least for GitHub Actions in [lurk-rs](https://github.com/lurk-lab/lurk-rs/pulls?q=is%3Apr+dependabot+), but it's unclear if the Cargo updates are working in either repo.

**Comment by huitseeker** [comment]
Dependabot doesn't support our rust-toolchain file which is antiquated:
https://github.com/lurk-lab/arecibo/network/updates/764791367

In our case, our non-toml rust-toolchain file is here because:
- we like pinning the rust version,
- we're still using [an old action](https://github.com/actions-rs/toolchain) to install the toolchain, which only supports this old format

We should instead use https://github.com/dtolnay/rust-toolchain except this is not great at supporting a pinned toolchain:
https://github.com/dtolnay/rust-toolchain/issues/92

One solution could be to go for a 'running' stable rust version, biting the bullet of the clippy incompatibilities at each release.
This probably also affects Lurk-rs.
