### ISSUE TITLE
Replace COO SpMVM by a CSR

### ISSUE THREAD

**Issue by huitseeker** [lurk-lab/arecibo#37]
https://github.com/lurk-lab/arecibo/pull/36 clearly shows that an SpMVM (Sparse Matrix-Vector Multiplication) is responsible for a significant amount of the folding time:
https://github.com/lurk-lab/arecibo/blob/c3608280054fd183c65873b88251e2710d483c3f/src/r1cs.rs#L169-L172

This operation is done on matrices in COO form, whereas the typical representation for such operations would be a CSR form ([wiki](https://en.wikipedia.org/wiki/Sparse_matrix#Compressed_sparse_row_(CSR,_CRS_or_Yale_format))). These matrices are created in the synthesis of `(Test)ShapeCS` :
https://github.com/lurk-lab/arecibo/blob/c3608280054fd183c65873b88251e2710d483c3f/src/bellpepper/r1cs.rs#L103-L104

Since those matrices are used only for SpMVM, we hope to replace all instances of COO by a CSR (unless something unexpected turns up, such as patterns of random access in the A, B, C matrices). 

The reason that we care about this representation is that it will make all the matrix elements relevant in a row of matrix-vector multiplication adjacent in memory, which opens a path to more performant code, amenable to LLVM's auto-vectorizer.

**Comment by porcuquine** [comment]
For clarity, it's my understanding that `mutliply_vec` is only used when creating a `CompressedSNARK`, so optimizing it will not increase folding costs. We also need to consider the implications of moving this work to the GPU when targeting a most-optimized `CompressedSNARK` proof. Finally, I believe the digest — the content of which affects the result of verification — is sensitive to this representation.

For all these reasons, we should consider *not* simply replacing the current representation but rather supplementing it. Specifically, in this proposal, we would continue to use the existing sparse representation of the shape, but also support computing (and caching) a representation more efficient for any particular `CompressedSNARK` proof implementation's needs.

The reason I think we should design for this generality is that we can anticipate predictably necessary optimizations to proving (both over time, with maturity, or due to a proliferation of distinct `CompressedSNARK`s with different design choices in their prover implementations) which suggest changes to the shape's representation. However, we need to ensure the parameter digest is insensitive to these changes. Otherwise standard verifiers will not be able to verify proofs emitted by provers on either side of such a representation change (in one instance) — and downstream cached parameters will lack a method for obtaining a unified shape-sensitive cache key, etc. (see: #34).

**Comment by porcuquine** [comment]
See UPDATE above. I now see that this does indeed affect folding costs. Nevertheless, the digest considerations remain.

I still think it may be best to leave the canonical representation as it is. I believe this will minimize digest-creation costs, though perhaps replacing them with conversion costs. There are two related benefits to this approach:
1. It avoids gratuitous incompatibility between pre-and-post optimization verifiers — which is useful in principal, even though we until digest representation stabilizes we will likely see necessary changes.
2. By making the effort to enable 1, we are forced to design a more future-proof mechanism for digests that are sensitive only to essential changes.

**Comment by huitseeker** [comment]
1. COO and CSR representations are both sparse. There is a bijection between them.
2. The CSR representation enjoys a 30y old specification across many languages and contexts.
3. It is the uncontested royal standard for arithmetic on sparse matrices, very much including on the GPU.
4. Arguably, it's an oddity of Nova to not use a matrix representation that allows easy slicing.

**Comment by porcuquine** [comment]
Changing seems fine if CSR is the right canonical representation. We should also target stabilized digests on the timeframe of deployed verifiers and proofs, if possible.

**Comment by winston-h-zhang** [comment]
I've read both conversations between this issue and the PR; I'll keep the discussion in mind as I implement this.
